def generate_ticket_pdf(
    pnr: str,
    passenger_name: str,
    email: str,
    phone: str,
    flight_number: str,
    airline_name: str,
    source_name: str,
    destination_name: str,
    departure_time: str,
    arrival_time: str,
    flight_date: str,
    seat_number: str,
    seat_class: str,
    gate_no: str,
    terminal_no: str,
    total_amount: float,
    payment_method: str,
    transaction_id: str,
    booking_status: str,
    baggage_allowance: str = "7kg Cabin + 15kg Check-in",
    trip_type: str = "One-Way",
    ticket_url: str = "",
) -> bytes:
    """Generate a dummy PDF bytes to avoid Vercel dependency crashes."""
    return b"%PDF-1.4\n%EOF"
